#!/bin/bash

# --- 02_run_samtools_parallel_ADAPTED.sh: Parallel Samtools Processing (SAM to Sorted BAM) ---

# --- Configuration ---
OUTPUT_DIR="bowtie2/alignment"
LOGS_DIR="bowtie2/logs"
THREADS_PER_JOB=4 # Threads used per Samtools instance

echo "--- Starting Parallel Samtools Processing ---"
echo "Threads per Job: $THREADS_PER_JOB. Max Concurrent Jobs: $(($SLURM_NTASKS / $THREADS_PER_JOB))"
echo "---------------------------------------------------"

# --- Function for Samtools ---
process_sam_to_bam() {
    local SAM_FILE="$1"
    
    # >>> ADAPTAÇÃO: Esta linha AGORA extrairá o novo nome curto,
    # ex: para o arquivo 'C_1.sam', o SAMPLE_NAME será 'C_1'
    local SAMPLE_NAME=$(basename "$SAM_FILE" .sam)
    
    # !!! MODULES: Uncomment and fix this line if you use Lmod/module load !!!
    # module load samtools/1.12
    
    local SORTED_BAM_OUTPUT="${OUTPUT_DIR}/${SAMPLE_NAME}.sorted.bam"
    local LOG_FILE="${LOGS_DIR}/${SAMPLE_NAME}.samtools.log"
    local THREADS="${THREADS_PER_JOB}"
    local BAM_TEMP="${OUTPUT_DIR}/${SAMPLE_NAME}.temp.bam"

    echo "[$(date +%H:%M:%S)] Starting Samtools: $SAMPLE_NAME"
    echo "Samtools Command Started at $(date)" > "$LOG_FILE"

    # 1. SAM to BAM Conversion
    saveCommand samtools view -b -@ "$THREADS" -o "$BAM_TEMP" "$SAM_FILE" 2>> "$LOG_FILE"
    
    if [ $? -ne 0 ]; then
        echo "!!! ERROR in Samtools VIEW for $SAMPLE_NAME." >> "$LOG_FILE"
        return 1
    fi
    
    # 2. Sorting BAM
    saveCommand samtools sort -@ "$THREADS" -o "$SORTED_BAM_OUTPUT" "$BAM_TEMP" 2>> "$LOG_FILE"
    
    if [ $? -ne 0 ]; then
        echo "!!! ERROR in Samtools SORT for $SAMPLE_NAME." >> "$LOG_FILE"
        return 1
    fi

    # 3. Indexing
    saveCommand samtools index "$SORTED_BAM_OUTPUT" 2>> "$LOG_FILE"
    
    if [ $? -ne 0 ]; then
        echo "!!! ERROR in Samtools INDEX for $SAMPLE_NAME." >> "$LOG_FILE"
        return 1
    fi
    
    # 4. Cleanup: Remove temporary files (SAM and intermediate BAM)
    rm "$SAM_FILE" "$BAM_TEMP"
    
    echo "[$(date +%H:%M:%S)] Samtools COMPLETED successfully for $SAMPLE_NAME. Final file: $SORTED_BAM_OUTPUT"
    return 0
}

# --- Parallel Execution ---
export -f process_sam_to_bam
export OUTPUT_DIR LOGS_DIR THREADS_PER_JOB

SLURM_NTASKS=${SLURM_NTASKS:-75} 
MAX_JOBS=$(($SLURM_NTASKS / $THREADS_PER_JOB))

# Find all .sam files generated by the first step
# NOTA: Agora ele procurará por C_1.sam, C_2.sam, etc.
SAM_LIST=$(find "$OUTPUT_DIR" -maxdepth 1 -name "*.sam")

if [ -z "$SAM_LIST" ]; then
    echo "!!! No .sam files found in $OUTPUT_DIR. Aborting Samtools step. !!!"
    exit 1
fi

# Run Samtools in parallel
echo "$SAM_LIST" | parallel \
    --jobs "$MAX_JOBS" \
    --joblog "$LOGS_DIR/samtools_job_status.log" \
    process_sam_to_bam {}

echo "--- End of Parallel Samtools Processing ---"